## Any changes to scanner.l and parser.y can be tested standalone using this Makefile.
#  make -f Makefile.parser clean && make -f Makefile.parser run

all: parser

lex.yy.c: scanner.l
	-flex scanner.l

parser.tab.c: parser.y
	-bison -d -v parser.y

parser: parser.tab.c lex.yy.c
	-gcc -Wall -D_DEBUG_PARSER -D_GNU_SOURCE -o parser parser.tab.c lex.yy.c
clean:
	-rm -f parser lex.yy.c parser.tab.c parser.tab.h lex.yy.o parser.output

run: parser
	-./parser < ../../tests/scripts/test.bng
